### ISSUE TITLE
Lacking the privilege to assign the issue to a team member

### ISSUE THREAD

**Issue by shirleyou** [wackerservices/Quickbooks-SalesTaxReclassifier#3]
Lacking the privilege to assign the issue to a team member

![image](https://github.com/user-attachments/assets/9fb20958-7ed5-4f34-a5f0-9feb2fe7e336)

**Comment by akritijain** [comment]
Gave you privilege now. Sorry about that @shirleyou

**Comment by shirleyou** [comment]
Yes, I can assign the issue now. Thank you
